---

- hosts: all
  become: true
  tasks:

  - name: install package
    package:
      name:
        - {{apache_package}}
        - {{php_package}}
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian, Ubuntu"]
