---
- name: My playbook
  hosts: all
  tasks:
     - name: Leaving a mark
       command: "touch /tmp/ansible_was_here"

     - name: Install vim-nox
       command: "apt install vim-nox"
       become: yes

     - name: install tmux
       command: "apt install tmux"
       become: yes

    -  name: install snapd
       command: "apt install snapd"
       become: yes