- name: install apache and php package
  tags: ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution in ["Debian, Ubuntu"]

- name: start and enable apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: restarted
    enabled: yes

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644