- name: install apache2 package
  tags: ubuntu
  apt:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution in ["Debian, Ubuntu"]

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644